services:
  restack-engine:
    image: ghcr.io/restackio/restack:main
    container_name: restack
    ports:
      - "5233:5233"  # GUI
      - "6233:6233"  # RPC
      - "7233:7233"  # Temporal
    restart: always

  docker-dind:
    image: docker:24-dind
    privileged: true
    # Disable TLS and run insecurely (for local dev only)
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--tls=false"]
    # No DOCKER_TLS_CERTDIR needed since we explicitly disabled TLS
    ports:
      - "2375:2375"

  backend:
    build: ./backend
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - RESTACK_ENGINE_ADDRESS=http://restack-engine:6233
      # If you still need the Docker host for build steps inside backend:
      - DOCKER_HOST=tcp://docker-dind:2375
    depends_on:
      - restack-engine
      - docker-dind
    ports:
      - "8000:8000"
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:8080"
    command: ["npm", "run", "dev"]
