# ./docker-compose.yml

services:
  restack-engine:
    image: ghcr.io/restackio/restack:main
    container_name: restack
    restart: always
    network_mode: host
    # environment:
    #   - OPTIONAL_ENV_VAR=...

  docker-dind:
    image: docker:24-dind
    privileged: true
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--tls=false"]
    network_mode: host

  backend:
    build: ./backend
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - DOCKER_HOST=tcp://localhost:2375
      - RESTACK_ENGINE_ADDRESS=localhost:6233
      # user env_vars need to be passed here from .env (and maybe worker?) somehow. also need to be passed into functions.py env_vars
    depends_on:
      - restack-engine
      - docker-dind
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    network_mode: host

  worker:
    build: ./backend
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - DOCKER_HOST=tcp://localhost:2375
      - RESTACK_ENGINE_ADDRESS=localhost:6233
      - RESTACK_TEMPORAL_ADDRESS=localhost:7233
    depends_on:
      - restack-engine
      - docker-dind
      - backend
    command: ["sh", "-c", "sleep 5 && poetry run python -m src.services"]
    network_mode: host

  frontend:
    build: ./frontend
    depends_on:
      - backend
    command: ["npm", "run", "dev"]
    network_mode: host
